name: Prepare Release

on:
  push:
    tags: [ "v[0-9]+.[0-9]+.[0-9]+*" ]

jobs:
  draftrelease:
    name: Draft Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "18.18.2"
      - name: Setup NPM
        run: npm install -g npm@10.2.4
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npx --no-install webpack
      - name: Draft Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: false
          files: |
              ./dist/notificationExamples.js
