name: Build Package

on:
  push:
    tags: [ "**", "!v[0-9]+.[0-9]+.[0-9]+*" ]

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "18.18.2"
      - name: Setup NPM
        run: npm install -g npm@10.2.4
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npx --no-install webpack
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/notificationExamples.js
          retention-days: 7
