name: Lint and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, edited, synchronize, reopened]

jobs:
  test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "18.18.2"
      - name: Setup NPM
        run: npm install -g npm@10.2.4
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npx --no-install eslint ./src ./tests --quiet
      - name: Test
        run: npx --no-install jest
